### ISSUE TITLE
CH get's cut off when you filter storage files by lookup tag

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#268]
Navigate to a sub company. Add a filter by lookup tag. When you do the CH will shift up as shown here, http://www.screencast.com/t/WWGRBp7U7. The only way to correct this is to refresh your page.

**Comment by EnlightenedCode** [comment]
@alanclayton this is a minor bug and might be fixed with the fix on this bug as well. https://github.com/Rise-Vision/storage-client/issues/281 it involves getting rid of common header in it's own iframe. this is what is causing a lot of "common header" dissappearing and scrolling issues. though they are minor

**Comment by fjvallarino** [comment]
@alanclayton This one does not seem to be happening anymore. Could you confirm?

**Comment by alanclayton** [comment]
@fjvallarino  Agreed. No longer an issue.
